### ISSUE TITLE
CSV parser could be generalised to other delimited formats

### ISSUE THREAD

**Issue by jbedo** [CountESS-Project/CountESS#2]
It would be nice to generalise the CSV parser to any arbitrary delimited data, allowing for example tab delimited tables to be read.

**Comment by nickzoic** [comment]
Yep, I agree ... or at least it should handle anything that the `pandas.read_csv` can handle.

I previously had a "regex reader" plugin, which would read a file and parse each line with a regex, but I ended up switching to the CSV reader + regex tool approach in the hopes of getting a bit more speed and also regexes aren't really able to fully deal with *all* CSVs (although almost always we're interested in a regular subset of CSV)

The regex reader may actually have been a better approach though, as for files which consist of a lot of oddly delimited numeric columns, using the CSV reader to build up an intermediate dataframe full of dtype "object" columns (eg: strings containing multiple numerics and delimiters, and then parsing that out to numeric columns in a separate step) is a bit of a waste.

So maybe we should include all three:

* CSV Reader for a "proper" csv/tsv reader which respects dialects and quoting and stuff
* Regex Reader which can't handle *all* the CSV weirdnesses but can handle more flexible delimiting
* Regex Tool which lets you also apply regexes to columns from other kinds of reader or from other intermediate steps.

This probably sounds like a duplication of effort but there can be multiple plugin classes per plugin file so Regex Reader and Regex Tool can potentially share code.

**Comment by nickzoic** [comment]
> but I ended up switching to the CSV reader + regex tool approach in the hopes of getting a bit more speed [...]

Oh and also that turned out not to be the case: `pandas.read_csv` isn't particularly fast and `dask.dataframe.read_csv` is really quite slow if you subsequently need to set an index.  So a Regex Reader plugin isn't going to be significantly slower.

**Comment by nickzoic** [comment]
OK for now I'm calling this one closed, we can add to CSVReader and/or RegexReader as new requirements come to light.
