### ISSUE TITLE
Error under Python 3.9

### ISSUE THREAD

**Issue by afrubin** [CountESS-Project/CountESS#4]
Launching the `countess_gui` under Python 3.9 returns the following error:
`Python version 3.9 does not allow writing union types as X | Y`

This could be fixed by importing from `__future__` or by requiring Python 3.10 or higher.

**Comment by nickzoic** [comment]
I pushed the requirement up to 3.10 ... 3.10 was released in October 2021 and Ubuntu 22.04 LTS is on 3.10.

I guess it depends on what versions are commonly out there on other distributions.  The only requirement for 3.10 that I know of is the union types syntax so it'd be no big deal to do the __future__ thing or to just use the older Union[] syntax which isn't so bad.

I'm not sure about the other python3s either.  It looks like pypy3 is only up to about 3.9 equivalence as well?

**Comment by genomematt** [comment]
Structural Pattern Matching is main 3.10 addition. Worth considering if we want to use.
Anaconda 2022.10 is Python 3.10 so from a packaging point of view seems 3.10 is mature enough to set as base. Pypy support only potential catch.

**Comment by nickzoic** [comment]
Yeah, we don't currently use that but it does look quite neat.  

My only concern with requiring `>= 3.10` is that, yeah, PyPy isn't quite there yet and the other Python3s I'm aware of are even further out of date.  But I'm not sure how widely used they are.

For now I've set the requirement to 3.10 and I'm  just leaving this here to remind me that either we can go with that or if we get feedback that it is inconvenient for users for us to require 3.10 we can back out to 3.9 or even 3.8 (eg: pypy 7.3.9) without too much trauma just by changing the annotation syntax or adding `from __future__ import annotations`.

Any older than that, no thanks :-)

**Comment by nickzoic** [comment]
OK well we've now had 2 people mention Python 3.9 so I guess it's worth remaining compatible.

**Comment by nickzoic** [comment]
This is merged in v0.0.32 and I'll consider dropping 3.9 in another 6 months or so.
